(part "104JT-025"
    (packageRef "104JT025")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "132")
    (property "Mouser_Part_Number" "954-104JT-025")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Semitec/104JT-025?qs=%252B6g0mu59x7KTJiBhCe3nqw%3D%3D")
    (property "Manufacturer_Name" "Semitec")
    (property "Manufacturer_Part_Number" "104JT-025")
    (property "Description" "NTC THERMISTORS 100KOHM 1% LENGT")
    (property "Datasheet_Link" "https://www.semitec-global.com/uploads/2022/01/P9-JT-Thermistor.pdf")
    (property "symbolName1" "104JT-025")
)
